# Form implementation generated from reading ui file 'source_config.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 150)
        Dialog.setMinimumSize(QtCore.QSize(450, 150))
        Dialog.setMaximumSize(QtCore.QSize(450, 150))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_source_configuration = QtWidgets.QFrame(Dialog)
        self.frame_source_configuration.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_source_configuration.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_source_configuration.setObjectName("frame_source_configuration")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_source_configuration)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_path_source = QtWidgets.QLineEdit(self.frame_source_configuration)
        self.lineEdit_path_source.setObjectName("lineEdit_path_source")
        self.gridLayout.addWidget(self.lineEdit_path_source, 0, 1, 1, 1)
        self.lineEdit_path_parameter = QtWidgets.QLineEdit(self.frame_source_configuration)
        self.lineEdit_path_parameter.setObjectName("lineEdit_path_parameter")
        self.gridLayout.addWidget(self.lineEdit_path_parameter, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_source_configuration)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_select_file = QtWidgets.QPushButton(self.frame_source_configuration)
        self.btn_select_file.setObjectName("btn_select_file")
        self.gridLayout.addWidget(self.btn_select_file, 0, 2, 1, 1)
        self.btn_select_param = QtWidgets.QPushButton(self.frame_source_configuration)
        self.btn_select_param.setObjectName("btn_select_param")
        self.gridLayout.addWidget(self.btn_select_param, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_source_configuration)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_check_port = QtWidgets.QPushButton(self.frame_source_configuration)
        self.btn_check_port.setObjectName("btn_check_port")
        self.horizontalLayout.addWidget(self.btn_check_port)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_source_configuration)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.frame_source_configuration)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Source Configuration"))
        self.label.setText(_translate("Dialog", "Source:"))
        self.btn_select_file.setText(_translate("Dialog", "Open File"))
        self.btn_select_param.setText(_translate("Dialog", "Open File"))
        self.label_2.setText(_translate("Dialog", "Parameter:"))
        self.btn_check_port.setText(_translate("Dialog", "Check port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
